task_id: quickbooks004
status: ready
title: Add a new dbt variable
notes: |-
  You have to exclude a bunch of source_relation columns because `dbt seed` imports empty strings as nulls.
descriptions:
  - key: base
    description: |-
      We are no longer using departments in our billing, so we should remove the using_department variable and all references to it. Do not remove it in the Fivetran source package.
author_name: test
author_email: test
difficulty: medium
category: jinja
tags:
  - dbt
  - schema-change
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Tables to compare for solution
solution_seeds:
  - table_name: int_quickbooks__vendor_credit_double_entry
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__sales_union
  - table_name: int_quickbooks__sales_receipt_transactions
  - table_name: int_quickbooks__sales_receipt_double_entry
  - table_name: int_quickbooks__refund_receipt_transactions
  - table_name: int_quickbooks__refund_receipt_double_entry
  - table_name: int_quickbooks__purchase_transactions
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__purchase_double_entry
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__payment_double_entry
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__journal_entry_transactions
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__journal_entry_double_entry
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__invoice_transactions
  - table_name: int_quickbooks__invoice_join
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__invoice_double_entry
  - table_name: int_quickbooks__expenses_union
  - table_name: int_quickbooks__deposit_transactions
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__credit_memo_transactions
  - table_name: int_quickbooks__credit_memo_double_entry
  - table_name: int_quickbooks__bill_transactions
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__bill_payment_double_entry
    exclude_columns:
    - source_relation 
  - table_name: int_quickbooks__bill_join
    exclude_columns:
    - source_relation
  - table_name: int_quickbooks__bill_double_entry
    exclude_columns:
    - source_relation
  - table_name: quickbooks__ap_ar_enhanced
    exclude_columns:
    - source_relation
    - customer_vendor_address_line

# Use shared database instead of local data files
database:
  source: shared
  name: quickbooks
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: quickbooks
  type: dbt