task_id: quickbooks002
status: ready
title: Remove dbt variable
notes: |-
descriptions:
  - key: base
    description: |-
      We are no longer using departments in our billing, so we should remove the using_department variable and all references to it. Do not remove it in the Fivetran source package.
author_name: test
author_email: test
difficulty: medium
category: jinja
tags:
  - dbt
  - schema-change
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Test setup script to run before dbt tests
test_setup: |-
  dbt run

# Tables to compare for solution
solution_seeds:
  - table_name: int_quickbooks__expenses_union
  - table_name: int_quickbooks__sales_union
  - table_name: quickbooks__ap_ar_enhanced
    exclude_columns:
    - source_relation
    - customer_vendor_address_line

# Use shared database instead of local data files
database:
  source: shared
  name: quickbooks
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: quickbooks
  type: dbt