task_id: analytics_engineering003
status: ready
title: Creates a new model that modifies a staging model.
descriptions:
  - key: base
    description: |-
      Create a model called "dim_customer" that renames id to customer_id, and makes that row a unique primary key.
author_name: test
author_email: test
difficulty: easy
category: model_creation
tags:
  - dbt
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Optional test setup script to run before dbt tests
test_setup: |-
  dbt run --select dim_customer

# Tables to compare for solution
solution_seeds:
  - table_name: dim_customer

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: analytics_engineering
  project_type: dbt
  project_name: analytics_engineering

- db_type: snowflake
  db_name: analytics_engineering
  project_type: dbt
  project_name: analytics_engineering
  migration_directory: analytics_engineering__duckdb_to_snowflake

- db_type: snowflake
  db_name: analytics_engineering
  project_type: dbt
  project_name: analytics_engineering
  migration_directory: analytics_engineering__duckdb_to_snowflake_dbtf