CREATE TABLE admin_data(id INTEGER, _fivetran_deleted BOOLEAN, _fivetran_synced VARCHAR, job_title INTEGER, email VARCHAR, "name" VARCHAR);;
CREATE TABLE company_history_data(id VARCHAR, updated_at TIMESTAMP, _fivetran_synced VARCHAR, company_id VARCHAR, created_at TIMESTAMP, industry INTEGER, last_request_at TIMESTAMP, monthly_spend INTEGER, plan_id INTEGER, plan_name INTEGER, remote_created_at INTEGER, session_count INTEGER, size INTEGER, user_count INTEGER, website INTEGER, "name" VARCHAR, _fivetran_active BOOLEAN, _fivetran_start TIMESTAMP, _fivetran_end TIMESTAMP);;
CREATE TABLE company_tag_history_data(company_id VARCHAR, company_updated_at TIMESTAMP, tag_id INTEGER, _fivetran_active BOOLEAN, _fivetran_synced VARCHAR, _fivetran_start TIMESTAMP, _fivetran_end TIMESTAMP);;
CREATE TABLE contact_company_history_data(company_id VARCHAR, contact_id VARCHAR, contact_updated_at TIMESTAMP, _fivetran_synced VARCHAR, _fivetran_active BOOLEAN, _fivetran_start TIMESTAMP, _fivetran_end TIMESTAMP);;
CREATE TABLE contact_history_data(id VARCHAR, updated_at TIMESTAMP, _fivetran_active BOOLEAN, _fivetran_synced VARCHAR, admin_id INTEGER, android_app_name INTEGER, android_app_version INTEGER, android_device INTEGER, android_last_seen_at INTEGER, android_os_version INTEGER, android_sdk_version INTEGER, browser INTEGER, browser_language INTEGER, browser_version INTEGER, created_at TIMESTAMP, custom_onboarding_step INTEGER, custom_organisation_id INTEGER, custom_organisation_name INTEGER, external_id VARCHAR, has_hard_bounced BOOLEAN, ios_app_name INTEGER, ios_app_version INTEGER, ios_device INTEGER, ios_last_seen_at INTEGER, ios_os_version INTEGER, ios_sdk_version INTEGER, language_override INTEGER, last_contacted_at TIMESTAMP, last_email_clicked_at TIMESTAMP, last_email_opened_at TIMESTAMP, last_replied_at INTEGER, last_seen_at INTEGER, location_city INTEGER, location_country INTEGER, location_region INTEGER, marked_email_as_spam BOOLEAN, os INTEGER, phone INTEGER, "role" VARCHAR, signed_up_at INTEGER, unsubscribed_from_emails BOOLEAN, workspace_id VARCHAR, avatar INTEGER, custom_job_title VARCHAR, email VARCHAR, "name" VARCHAR, _fivetran_start TIMESTAMP, _fivetran_end TIMESTAMP);;
CREATE TABLE contact_tag_history_data(contact_id VARCHAR, contact_updated_at TIMESTAMP, tag_id INTEGER, _fivetran_synced VARCHAR, _fivetran_start TIMESTAMP, _fivetran_end TIMESTAMP, _fivetran_active BOOLEAN);;
CREATE TABLE conversation_contact_history_data(contact_id VARCHAR, conversation_id INTEGER, conversation_updated_at TIMESTAMP, _fivetran_synced VARCHAR, _fivetran_start TIMESTAMP, _fivetran_end TIMESTAMP, _fivetran_active BOOLEAN);;
CREATE TABLE conversation_history_data(id INTEGER, updated_at TIMESTAMP, _fivetran_synced VARCHAR, assignee_id INTEGER, assignee_type VARCHAR, conversation_rating_created_at INTEGER, conversation_rating_remark INTEGER, conversation_rating_value INTEGER, created_at TIMESTAMP, first_contact_reply_created_at TIMESTAMP, first_contact_reply_type VARCHAR, priority VARCHAR, "read" BOOLEAN, sla_name INTEGER, sla_status INTEGER, snoozed_until INTEGER, source_author_id VARCHAR, source_author_type VARCHAR, source_delivered_as VARCHAR, source_id INTEGER, source_type VARCHAR, state VARCHAR, waiting_since TIMESTAMP, first_contact_reply_url VARCHAR, source_body VARCHAR, source_subject VARCHAR, source_url VARCHAR, _fivetran_start TIMESTAMP, _fivetran_end TIMESTAMP, _fivetran_active BOOLEAN);;
CREATE TABLE conversation_part_history_data(id INTEGER, updated_at TIMESTAMP, _fivetran_synced VARCHAR, assigned_to_id INTEGER, assigned_to_type INTEGER, author_id INTEGER, author_type VARCHAR, conversation_id INTEGER, conversation_updated_at TIMESTAMP, created_at TIMESTAMP, notified_at TIMESTAMP, part_type VARCHAR, body VARCHAR, _fivetran_start TIMESTAMP, _fivetran_end VARCHAR, _fivetran_active BOOLEAN);;
CREATE TABLE conversation_tag_history_data(tag_id INTEGER, conversation_id INTEGER, conversation_updated_at VARCHAR, _fivetran_start VARCHAR, _fivetran_end VARCHAR, _fivetran_active BOOLEAN);;
CREATE TABLE tag_data(id INTEGER, _fivetran_deleted BOOLEAN, _fivetran_synced VARCHAR, "name" VARCHAR);;
CREATE TABLE team_admin_data(admin_id INTEGER, team_id INTEGER, _fivetran_deleted BOOLEAN, _fivetran_synced TIMESTAMP);;
CREATE TABLE team_data(id INTEGER, "name" VARCHAR, _fivetran_deleted BOOLEAN, _fivetran_synced TIMESTAMP);;

