FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    tmux asciinema \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dbt-core==1.9.6 \
    dbt-duckdb==1.9.3 \
    duckdb==1.3.0 \
    pyyaml>=6.0 \
    uv>=0.7


# Set up workspace

RUN mkdir -p /installed-agent /scripts /oracle/solutions /oracle /app /app/setup /app/migrations /seeds /solutions /logs /tests
WORKDIR /app

CMD ["bash"]