task_id: airbnb008
status: ready
description: Fix a syntax error in the schema.yml file.
notes: |-
prompts:
  - key: base
    prompt: |-
      The project is broken.
author_name: test
author_email: test
difficulty: easy
category: debug
tags:
  - dbt
timeout_seconds: 500

# Test setup script to run before dbt tests
test_setup: |-
  dbt run

# Tables to compare for solution
solution_seeds:
  - table_name: mom_agg_reviews
  - table_name: monthly_agg_reviews

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: airbnb
  project_type: dbt
  project_name: airbnb

- db_type: snowflake
  db_name: airbnb
  project_type: dbt
  project_name: airbnb
  migration_directory: airbnb__duckdb_to_snowflake

- db_type: snowflake
  db_name: airbnb
  project_type: dbt-fusion
  project_name: airbnb
  migration_directory: airbnb__duckdb_to_snowflake_dbtf