task_id: airbnb008
status: ready
title: Fix a syntax error in the schema.yml file.
notes: |-
descriptions:
  - key: base
    description: |-
      The project is broken.
author_name: test
author_email: test
difficulty: easy
category: debug
tags:
  - dbt
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Test setup script to run before dbt tests
test_setup: |-
  dbt run

# Tables to compare for solution
solution_seeds:
  - table_name: mom_agg_reviews
  - table_name: monthly_agg_reviews

# Use shared database instead of local data files
database:
  source: shared
  name: airbnb
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: airbnb
  type: dbt