task_id: shopify-analytics
title: Shopify Product and Shop Performance Analytics
descriptions:
  - key: base
    description: |-
      Create two tables: one that pulls together product data like total sales, refunds, discounts, and taxes, and another that tracks daily shop performance, including orders, abandoned checkouts, and fulfillment statuses.
author_name: test
author_email: test
difficulty: easy
category: data-transformation
tags:
  - dbt
  - aggregation
  - joins
  - e-commerce
  - analytics
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Use shared database instead of local data files
database:
  source: shared
  name: shopify
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: shopify_analytics
  type: dbt