task_id: asana003
status: ready
description: Fix our data to match new Fivetran package.
notes: |-
  This is from a mismatch in the Fivetran Asana package, where the underlying data no longer matches the current package.
prompts:
  - key: base
    prompt: |-
      This project is erroring because Fivetran updated their Asana package. Please modify our data to match this new package.
author_name: test
author_email: test
difficulty: medium
category: debug
tags:
  - dbt
  - data

# Test setup script to run before dbt tests
test_setup: |-
  dbt deps
  dbt run

# Tables to compare for solution
solution_seeds:
  - table_name: asana__task
    exclude_columns:
      - days_open

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: asana
  project_type: dbt
  project_name: asana