task_id: f1004
status: dev
title: Fix string matching issue.
notes: |-
descriptions:
  - key: base
    description: |-
      Several columns in the "finishes_by_driver" are showing 0 results for every driver. Can you figure out what's happening and fix it?
author_name: test
author_email: test
difficulty: medium
category: model-creation
tags:
  - dbt
  - data-quality
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Tables to compare for solution
solution_seeds:
  - table_name: finishes_by_driver

# Use shared database instead of local data files
database:
  source: shared
  name: f1
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: f1
  type: dbt