task_id: f1004
status: ready
description: Fix string matching issue.
notes: |-
prompts:
  - key: base
    prompt: |-
      Several columns in the "finishes_by_driver" are showing 0 results for every driver. Can you figure out what's happening, fix it, and update the table?
author_name: test
author_email: test
difficulty: medium
category: model-creation
tags:
  - dbt
  - data-quality
timeout_seconds: 500

# Tables to compare for solution
solution_seeds:
  - table_name: finishes_by_driver

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: f1
  project_type: dbt
  project_name: f1

- db_type: snowflake
  db_name: f1
  project_type: dbt
  project_name: f1
  migration_directory: f1__duckdb_to_snowflake