task_id: airbnb006
status: ready
title: Update misnamed CTEs.
notes: |-
  Need to include fct_reviews in the solution seeds, but it's too big.
descriptions:
  - key: base
    description: |-
      Update the CTEs in the models to be named correctly.
author_name: test
author_email: test
difficulty: medium
category: hygiene
tags:
  - dbt
  - naming
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Test setup script to run before dbt tests
test_setup: |-
  dbt run --select fct_reviews dim_hosts

# Tables to compare for solution
solution_seeds:
  - table_name: dim_listings
  - table_name: dim_hosts

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: airbnb
  project_type: dbt
  project_name: airbnb