asana-duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "./asana.duckdb"

asana-snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      ## Added by when task is created
      account: <account>
      user: <user>
      password: <password>
      role: <role>
      database: <database>
      schema: <schema>
      warehouse: <warehouse>