task_id: f1007
status: ready
description: Fix a join issue
notes: |-
  Check to make sure this works when you fix the bug that breaks multi-version tasks. A join that should be a left join is an inner join.
prompts:
  - key: base
    prompt: |-
      Something is wrong with the staging results table, where it's missing a lot of rows. Can you figure out why, fix it, and update the table?
  - key: medium
    prompt: |-
      The driver_wins_by_season table is suddenly empty. Can you figure out why, fix it, and update the table?
  - key: hard
    prompt: |-
      A lot of stats models are showing very different values and everything things broken. Can you figure out why, fix it, and update the tables?
author_name: test
author_email: test
difficulty: medium
category: debugging
tags:
  - dbt
  - data-quality

# Tables to compare for solution
solution_seeds:
  - table_name: driver_wins_by_season
  - table_name: stg_f1_dataset__results
  - table_name: finishes_by_driver

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: f1
  project_type: dbt
  project_name: f1

- db_type: snowflake
  db_name: f1
  project_type: dbt
  project_name: f1
  migration_directory: f1__duckdb_to_snowflake

- db_type: snowflake
  db_name: f1
  project_type: dbt-fusion
  project_name: f1
  migration_directory: f1__duckdb_to_snowflake