task_id: airbnb009
status: dev
title: foo
notes: |-
descriptions:
  - key: base
    description: |-
      In mom_agg_reviews, there should be a row for every day. Right now, some days are missing. Can you identify why these days are missing, and fix that model?
author_name: test
author_email: test
difficulty: medium
category: logic
tags:
  - dbt  
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Use shared database instead of local data files
database:
  source: shared
  name: airbnb
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: airbnb
  type: dbt