version: '3.8'

services:
  client:
    build:
      context: ${ADE_BENCH_BUILD_CONTEXT_DIR}
      dockerfile: Dockerfile
    image: ${ADE_BENCH_CLIENT_IMAGE_NAME}
    container_name: ${ADE_BENCH_CLIENT_CONTAINER_NAME}
    command: ["sh", "-c", "sleep infinity"]
    environment:
      - TEST_DIR=${ADE_BENCH_TEST_DIR}
      - DBT_PROFILES_DIR=/root/.dbt
      - DBT_PROJECT_DIR=/dbt_project
      - DATABASE_TYPE=${ADE_BENCH_DB_TYPE}
      - DATABASE_NAME=${ADE_BENCH_DB_NAME}
    volumes:
      - ${ADE_BENCH_LOGS_PATH}:${ADE_BENCH_CONTAINER_LOGS_PATH}
      - ${ADE_BENCH_DBT_PROJECT_PATH}:/dbt_project
    networks:
      - ade-network
    depends_on:
      database:
        condition: service_healthy

  database:
    image: duckdb/duckdb:latest
    container_name: ${ADE_BENCH_NAME_PREFIX}__database
    command: ["sh", "-c", "mkdir -p /data && sleep infinity"]
    volumes:
      - ${ADE_BENCH_DATA_PATH}:/data
    networks:
      - ade-network
    healthcheck:
      test: ["CMD", "test", "-f", "/data/${ADE_BENCH_DB_NAME}.duckdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  ade-network:
    name: ${ADE_BENCH_NAME_PREFIX}__network
    driver: bridge