task_id: template
status: dev
description: Template
notes: |-
  [dev notes]
prompts:
  - key: base
    prompt: |-
      Do some stuff.
author_name: test
author_email: test
difficulty: easy
category: data-transformation
tags:
  - dbt
  - aggregation
  - joins
  - e-commerce
  - analytics
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Optional test setup script to run before dbt tests
# test_setup: |-
#   dbt run

# Tables to compare for solution
# solution_seeds:
#   - template__model
#   - table_name: another_model
#     exclude_columns:
#       - insertion_timestamp
#     exclude_tests:
#       - equality_test

# Use shared database instead of local data files
database:
  source: shared
  name: template
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: template
  type: dbt