task_id: template
status: dev
title: Template
notes: |-
  [dev notes]
descriptions:
  - key: base
    description: |-
      Do some stuff.
author_name: test
author_email: test
difficulty: easy
category: data-transformation
tags:
  - dbt
  - aggregation
  - joins
  - e-commerce
  - analytics
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Optional test setup script to run before dbt tests
# test_setup: |-
#   dbt run

# Tables to compare for solution
# solution_seeds:
#   - template__model

# Use shared database instead of local data files
database:
  source: shared
  name: template
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: template
  type: dbt