config-version: 2
name: 'workday'
version: '0.2.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

profile: 'workday-duckdb'



models:
  +materialized: table  # workday_history 模型也存为 'table'

vars:
  workday_schema: main
  workday:
    workday_job_profile_identifier: "workday_job_profile_data"
    workday_job_family_job_profile_identifier: "workday_job_family_job_profile_data"
    workday_job_family_job_family_group_identifier: "workday_job_family_job_family_group_data"
    workday_job_family_identifier: "workday_job_family_data"
    workday_job_family_group_identifier: "workday_job_family_group_data"
    workday_organization_role_identifier: "workday_organization_role_data"
    workday_organization_role_worker_identifier: "workday_organization_role_worker_data"
    workday_organization_job_family_identifier: "workday_organization_job_family_data"
    workday_organization_identifier: "workday_organization_data"
    workday_position_organization_identifier: "workday_position_organization_data"
    workday_position_identifier: "workday_position_data"
    workday_position_job_profile_identifier: "workday_position_job_profile_data"
    workday_worker_history_identifier: "workday_worker_history_data"
    workday_personal_information_history_identifier: "workday_personal_information_history_data"
    workday_person_name_identifier: "workday_person_name_data"
    workday_personal_information_ethnicity_identifier: "workday_personal_information_ethnicity_data"
    workday_military_service_identifier: "workday_military_service_data"
    workday_person_contact_email_address_identifier: "workday_person_contact_email_address_data"
    workday_worker_position_history_identifier: "workday_worker_position_history_data"
    workday_worker_leave_status_identifier: "workday_worker_leave_status_data"
    workday_worker_position_organization_history_identifier: "workday_worker_position_organization_history_data"


seeds:
  +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"