task_id: workday001
status: open
title: Template
descriptions:
  - key: base
    description: |-
      Do some stuff.
author_name: test
author_email: test
difficulty: easy
category: data-transformation
tags:
  - dbt
  - aggregation
  - joins
  - e-commerce
  - analytics
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: workday
  project_type: dbt
  project_name: workday