task_id: template
title: Template
descriptions:
  - key: base
    description: |-
      Do some stuff.
author_name: test
author_email: test
difficulty: easy
category: data-transformation
tags:
  - dbt
  - aggregation
  - joins
  - e-commerce
  - analytics
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Use shared database instead of local data files
database:
  source: shared
  name: workday
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: workday
  type: dbt