CREATE TABLE RAW_HOSTS(ID INTEGER, "NAME" VARCHAR, IS_SUPERHOST VARCHAR, CREATED_AT TIMESTAMP, UPDATED_AT TIMESTAMP);;
CREATE TABLE RAW_LISTINGS(ID INTEGER, LISTING_URL VARCHAR, "NAME" VARCHAR, ROOM_TYPE VARCHAR, MINIMUM_NIGHTS INTEGER, HOST_ID INTEGER, PRICE VARCHAR, CREATED_AT TIMESTAMP, UPDATED_AT TIMESTAMP);;
CREATE TABLE RAW_REVIEWS(LISTING_ID INTEGER, DATE TIMESTAMP, REVIEWER_NAME VARCHAR, "COMMENTS" VARCHAR, SENTIMENT VARCHAR);;

