task_id: quickbooks002
status: ready
title: Remove dbt variable and solve data issue
notes: |-
  Same as quickbooks002, but the error from quickbooks001 has not been fixed yet.
descriptions:
  - key: base
    description: |-
      We are no longer using departments in our billing, so we should remove the using_department variable and all references to it. Do not remove it in the Fivetran source package.
author_name: test
author_email: test
difficulty: hard
category: jinja
tags:
  - dbt
  - schema-change
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Tables to compare for solution
solution_seeds:
  - table_name: int_quickbooks__refund_receipt_transactions
  - table_name: int_quickbooks__sales_receipt_transactions
  - table_name: int_quickbooks__invoice_double_entry
  - table_name: int_quickbooks__expenses_union
  - table_name: int_quickbooks__sales_union
  - table_name: quickbooks__ap_ar_enhanced
    exclude_columns:
    - source_relation
    - customer_vendor_address_line

# Use shared database instead of local data files
database:
  source: shared
  name: quickbooks
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: quickbooks
  type: dbt