task_id: f1002
status: ready
description: Add new stats models based on yml config
notes: |-
  Driver names are excluded from comparisons because the results are limited to top 20, there are ties in the 20th position, and different drivers sometimes are chosen in the top 20.
  Solving this issue is in f1003
prompts:
  - key: base
    prompt: |-
      There are four models defined in the __stats.yml config. Create new models for each of these so that they fit the yml config.
author_name: test
author_email: test
difficulty: hard
category: model-creation
tags:
  - dbt
timeout_seconds: 500

# Test setup script to run before dbt tests
test_setup: |-
  dbt run

# Tables to compare for solution
solution_seeds:
  - table_name: finishes_by_driver
  - table_name: most_podiums
    exclude_columns:
    - driver_full_name
  - table_name: most_pole_positions
    exclude_columns:
    - driver_full_name
  - table_name: most_fastest_laps
    exclude_columns:
    - driver_full_name

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: f1
  project_type: dbt
  project_name: f1

- db_type: snowflake
  db_name: f1
  project_type: dbt
  project_name: f1
  migration_directory: f1__duckdb_to_snowflake