task_id: f1002
status: ready
title: Add new stats models based on yml config
notes: |-
  Driver names are excluded from comparisons because the results are limited to top 20, there are ties in the 20th position, and different drivers sometimes are chosen in the top 20. 
  Solving this issue is in f1003
descriptions:
  - key: base
    description: |-
      There are four models defined in the __stats.yml config. Create new models for each of these so that they fit the yml config.
author_name: test
author_email: test
difficulty: hard
category: model-creation
tags:
  - dbt
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Test setup script to run before dbt tests
test_setup: |-
  dbt run

# Tables to compare for solution
solution_seeds:
  - table_name: finishes_by_driver
  - table_name: most_podiums
    exclude_columns:
    - driver_full_name
  - table_name: most_pole_positions
    exclude_columns:
    - driver_full_name
  - table_name: most_fastest_laps
    exclude_columns:
    - driver_full_name

# Use shared database instead of local data files
database:
  source: shared
  name: f1
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: f1
  type: dbt