task_id: f1002
status: dev
title: Add new stats models based on yml config
notes: |-
  For some reason, the most_fastest_laps equality test fails, but not in dev?
descriptions:
  - key: base
    description: |-
      There are four models defined in the __stats.yml config. Create new models for each of these so that they fit the yml config.
author_name: test
author_email: test
difficulty: hard
category: model-creation
tags:
  - dbt
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Tables to compare for solution
solution_seeds:
  - table_name: finishes_by_driver
  - table_name: most_podiums
  - table_name: most_pole_positions
  - table_name: most_fastest_laps


# Use shared database instead of local data files
database:
  source: shared
  name: f1
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: f1
  type: dbt