task_id: analytics_engineering001
status: ready
description: A dummy task that doesn't need to do anything to pass. It how many columns are in the project, and passes the test if the same number is returned.
prompts:
  - key: base
    prompt: |-
      This is a dbt project. Do not make any changes.
author_name: test
author_email: test
difficulty: easy
category: diagnostic
tags:
  - dbt
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: analytics_engineering
  project_type: dbt
  project_name: analytics_engineering