task_id: f1006
status: ready
title: Fix a calculation error that requires a semantic understanding of data, with no example of correction.
notes: |-
  This task changes both driver_points andconstructor_points.
descriptions:
  - key: base
    description: |-
      Someone noticed that the "points" columns in constructor_points.sql and driver_points.sql look way too high. Can you figure out what's wrong and fix it?
  - key: hard
    description: |-
      Someone noticed that the results in constructor_points.sql and driver_points.sql look wrong. Can you figure out what's wrong and fix it?
author_name: test
author_email: test
difficulty: hard
category: model-creation
tags:
  - dbt
  - data-quality
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Tables to compare for solution
solution_seeds:
  - table_name: constructor_points
  - table_name: driver_points

# Use shared database instead of local data files
database:
  source: shared
  name: f1
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: f1
  type: dbt