task_id: f1006
status: ready
description: Fix a calculation error that requires a semantic understanding of data, with no example of correction.
notes: |-
  This task changes both driver_points andconstructor_points.
prompts:
  - key: base
    prompt: |-
      Someone noticed that the "points" columns in constructor_points.sql and driver_points.sql look way too high. Can you figure out what's wrong, fix it, and update the table?
  - key: hard
    prompt: |-
      Someone noticed that the results in constructor_points.sql and driver_points.sql look wrong. Can you figure out what's wrong, fix it, and update the table?
author_name: test
author_email: test
difficulty: hard
category: model-creation
tags:
  - dbt
  - data-quality
timeout_seconds: 500

# Tables to compare for solution
solution_seeds:
  - table_name: constructor_points
  - table_name: driver_points

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: f1
  project_type: dbt
  project_name: f1

- db_type: snowflake
  db_name: f1
  project_type: dbt
  project_name: f1
  migration_directory: f1__duckdb_to_snowflake