#!/bin/bash

## remove old models
rm -r models/agg
rm -r models/dim
rm -r models/fact

## Add schema.yml to models directory
cat > models/schema.yml << 'EOF'
version: 2

models:
  # Aggregation Models
  - name: listing_agg_nps_reviews
    description: |
      Calculates NPS score for each listing, using review sentiment as promoter / detractor
    config:
      materialized: table
    columns:
      - name: listing_id
      - name: listing_name
      - name: room_type
      - name: nps_total
        description: "Lifetime NPS score of listing"        
      - name: reviews_total
        description: "Total number of reviews for the listing"

  - name: daily_agg_nps_reviews
    description: |
      Calculates daily and rolling 28-day NPS scores, using review sentiment as promoter / detractor
    config:
      materialized: incremental
    columns:
      - name: review_date
      - name: nps_daily
      - name: reviews_daily
      - name: nps_28d
        description: "NPS score over last 28 days"
      - name: reviews_28d
        description: "Reviews over last 28 days"

  # Dimension Models
  - name: dim_hosts
    config:
      materialized: table
    columns:
      - name: HOST_ID
      - name: HOST_NAME
        description: "Name of the host (defaults to 'anonymous' if null)"
      - name: IS_SUPERHOST
      - name: CREATED_AT
      - name: UPDATED_AT

  - name: dim_listings
    config:
      materialized: table
    columns:
      - name: LISTING_ID
      - name: LISTING_NAME
      - name: MINIMUM_NIGHTS
        description: "Minimum number of nights required for booking (defaults to 1 if 0)"
      - name: HOST_ID
      - name: ROOM_TYPE
      - name: PRICE
        description: "Numeric per night"
      - name: CREATED_AT
      - name: UPDATED_AT

  - name: dim_listings_hosts
    description: |
    config:
      materialized: table
    columns:
      - name: CREATED_AT
        description: Listing created at
      - name: UPDATED_AT
        description: "Most recent update timestamp between listing and host records"
      - name: LISTING_ID
      - name: LISTING_NAME
      - name: ROOM_TYPE
      - name: minimum_nights
      - name: PRICE
      - name: HOST_ID
      - name: HOST_NAME
      - name: IS_SUPERHOST
      - name: LISTING_HOST_ID
        description: "Surrogate key from listing and host id, generated by dbt macro"

  # Fact Models
  - name: fct_reviews
    description: |
      Reviews from source table. Only includes reviews that have text.
    config:
      materialized: incremental
EOF