task_id: airbnb007
status: ready
title: Create several models based on a schema.yml file.
notes: |-
descriptions:
  - key: base
    description: |-
      Create the models described in the schema.yml file.
author_name: test
author_email: test
difficulty: hard
category: model-creation
tags:
  - dbt
  - naming 
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Tables to compare for solution
solution_seeds:
  - table_name: dim_hosts
  - table_name: dim_listings
  - table_name: dim_listings_hosts
  - table_name: daily_agg_nps_reviews
  - table_name: listing_agg_nps_reviews

# Use shared database instead of local data files
database:
  source: shared
  name: airbnb
  type: duckdb

# Use shared project instead of local project
project:
  source: shared
  name: airbnb
  type: dbt