task_id: airbnb007
status: ready
description: Create several models based on a schema.yml file.
notes: |-
prompts:
  - key: base
    prompt: |-
      Create the models described in the schema.yml file.
author_name: test
author_email: test
difficulty: hard
tags:
  - dbt
  - model-creation
  - dbt-materialization
  - dbt-project-configuration

# Tables to compare for solution
solution_seeds:
  - table_name: dim_hosts
  - table_name: dim_listings
  - table_name: dim_listings_hosts
  - table_name: daily_agg_nps_reviews
    exclude_tests:
      - equality_test
  - table_name: listing_agg_nps_reviews
    exclude_tests:
      - equality_test

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: airbnb
  project_type: dbt
  project_name: airbnb

- db_type: snowflake
  db_name: airbnb
  project_type: dbt
  project_name: airbnb
  migration_directory: airbnb__duckdb_to_snowflake

- db_type: snowflake
  db_name: airbnb
  project_type: dbt-fusion
  project_name: airbnb
  migration_directory: airbnb__duckdb_to_snowflake_dbtf