task_id: airbnb003
status: ready
title: Update dbt models to be views
notes: |-
  I want to include a test to check for src_reviews but need to figure out how limit the table size.
descriptions:
  - key: base
    description: |-
      Update the all the source models to be views.
author_name: test
author_email: test
difficulty: easy
category: data-transformation
tags:
  - dbt
  - aggregation
  - joins
  - e-commerce
  - analytics
timeout_seconds: 500
parser_name: dbt
db_type: duckdb

# Test setup script to run before dbt tests
test_setup: |-
  dbt run --select src_hosts src_listings src_reviews

# Tables to compare for solution
solution_seeds:
  - table_name: src_hosts
  - table_name: src_listings
  # - src_reviews

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: airbnb
  project_type: dbt
  project_name: airbnb